package io.engenious.sift.exceptions

class ConfigurationException(message: String, cause: Throwable) : RuntimeException(message, cause)
